# Site settings
name: Johan Rosenhed
description: Game Designer Generalist
avatar: /Images/Profile.JPG
url: "https://Mikael925.github.io"
baseurl: ""

# Navigation links
navigation:
  - title: About Me
    url: /
  - title: Narrative Design
    url: /narrative-design/
  - title: Level Design
    url: /level-design/
  - title: Sound Design
    url: /sound-design/
  - title: Systems Design
    url: /systems-design/
  - title: Generalist
    url: /generalist/

# Footer links
footer-links:
  dribbble:
  email: Mikael925@gmail.com
  facebook:
  flickr:
  github: https://github.com/Mikael925
  instagram: 
  linkedin: https://www.linkedin.com/in/mikael925/
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube: https://www.youtube.com/@mikael925
  googleplus:

# Build settings
permalink: /:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
